title: "Roberto González Fontenla. Excel, Python, IA"
description: "Blog sobre tecnología, aprendizaje y bienestar digital."
theme: minima # Es un tema básico que viene por defecto
show_excerpts: true
